name: lint

on: [pull_request]
jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - name: "Lint the code"
        uses: muxee/clang-tidy-action@master
        with:
          args: -checks=*
