name: lint

on: 
  pull_request:
    branches:
      - master
  
jobs:
  linter_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: clang-tidy check
      - uses: muxee/clang-tidy-action@0.0.1-rc1
      - run: echo Hello, world!
