name: Test homework functionality

on: 
  project_card:
    types: [moved]
jobs:
  check-homework:
    runs-on: ubuntu-latest
    container:
      volumes: 
        - /home/runner/work/CITest/tests:/github/workspace/tests
    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
      with:
        repository: smay1613/Luxoft-Training-Center-CPP-003-Tests
        ref: refs/heads/master
        token: ${{ secrets.ACCESS_TOKEN }}
        path: tests
    - name: "Homework check"
      uses: smay1613/homework-checker-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         DEBUG: "true"
