name: Test homework functionality

on: 
  project_card:
    types: [moved]
jobs:
  check-homework:
    runs-on: ubuntu-latest
    steps:
    - uses: smay1613/homework-checker-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DEBUG: "true"
