name: Test homework functionality

on: 
  project_card:
    types: [moved]
jobs:
  check-homework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: smay1613/Luxoft-Training-Center-CPP-003-Tests
        ref: refs/heads/master
        token: ${{ secrets.ACCESS_TOKEN }}
        path: CITest/tests
    - uses: smay1613/homework-checker-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         DEBUG: "true"
