name: Pull request name lint

on: [pull_request]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "@${pull_request.user.login} this issue was automatically closed because it did not follow the issue template"
        pr-pattern: 'Task.*\d+.*\[card-\d+\]'
